# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
env:
  - PROJECT_DESCRIPTION=Warpdir is a simple command line tool to create and manage shortcuts to directories
  - PROJECT_HOMEPAGE=https://github.com/nousefreak/warpdir
  - LICENSE=MIT

version: 1

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

checksum:
  name_template: 'checksums.txt'

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - repository:
      owner: nousefreak
      name: homebrew-brew
    folder: Formula
    homepage: "{{ .Env.PROJECT_HOMEPAGE }}"
    description: "{{ .Env.PROJECT_DESCRIPTION }}"
    license: "{{ .Env.LICENSE }}"
    test: |
      system "#{bin}/{{ .ProjectName }} help"
    dependencies: []
    install: |-
      bin.install "{{ .ProjectName }}"
